version: '3.7'
# DevelopMent

services:
  practice-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/practice/src
    env_file:
      - ./.env

  practice-db:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'practice'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
