#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"



REGEX='/DOCS|FEAT|FIX|HOTFIX|CHORE: \(.+\) .+ */'
MSG_FILE=`cat $1`

echo $MSG_FILE

if ! [[ $MSG_FILE =~ $REGEX ]]; then
    echo "[ERROR] 커밋 메시지가 형태에 맞지 않습니다."
    echo "==========="
    echo "[INFO] ({COMMIT_TYPE}): ({ISSUE}) {MESSAGE}"
    echo "[INFO] COMMIT_TYPE "
    echo "- DOCS"
    echo "- FEAT"
    echo "- FIX"
    echo "- HOTFIX"
    echo "- CHORE"
    exit 1
fi