#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Git Hook from .husky"

yarn lint-staged && yarn test

BRANCH=`git rev-parse --abbrev-ref HEAD`

# if [ "$BRANCH" == "master" ] || [ "$BRANCH" == "dev"] 
# then
#     echo "<$BRANCH> 브랜치에는 커밋이 불가능합니다."
#     echo "<$BRANCH> 브랜치가 아닌 다른 브랜치에서 커밋을하세요."
#     exit 1
# fi